#!/bin/sh
# shellcheck disable=SC2154
set -e

#******************************************************************************
#	Copyright (C) 2022-2025  Henrique Almeida <me@h3nc4.com>

#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.

#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
#******************************************************************************

# This script must be run by your user on a fresh Debian/Devuan net-install
# Preferrably, select no packages during the installation process

while getopts "odgvhxwm:" opt; do
	case "${opt}" in
	o) OPTIONALS=opt ;;
	d) DEVPACKS=dev ;;
	g) GAMES=games ;;
	v) VIRTUALIZATION=virt ;;
	h) HEADLESS=1 ;;
	x) XORG=xorg ;;
	w) WAYLAND=wayl ;;
	m) MIRROR="${OPTARG}" ;;
	*)
		echo "Usage: $0 [-o] [-d] [-g] [-v] [-h] [-x] [-w] [-m <mirror>]
  -o    Include extra software
  -d    Include development software
  -g    Include gaming software
  -v    Include virtualization software
  -h    Headless only (disables -x and -w)
  -x    Include Xorg (on if neither -w or -h is passed) (ignored if -h is set)
  -w    Include Wayland (ignored if -h is set)
  -m    Specify a mirror" >&2
		exit 1
		;;
	esac
done

if [ -n "${HEADLESS}" ] && { [ -n "${XORG}" ] || [ -n "${WAYLAND}" ]; }; then
	echo "Warning: -h (headless) overrides -x and -w; graphical options will be ignored." >&2
fi

if [ -n "${HEADLESS}" ]; then
	XORG=
	WAYLAND=
	GUI=
else
	if [ -z "${WAYLAND}" ]; then
		XORG=${XORG:-"xorg"}
	fi
	GUI=gui
fi

# If no mirror is provided, set a default
if command -v systemctl >/dev/null 2>&1 || [ "$(cat /proc/1/comm)" = "systemd" ]; then
	ONSYSTEMD=y
	MIRROR=${MIRROR:-"http://deb.debian.org/debian/"}
	DEB_KEYRING=${DEB_KEYRING:-"/usr/share/keyrings/debian-archive-keyring.gpg"}
else
	MIRROR=${MIRROR:-"http://br.deb.devuan.org/merged"}
	DEB_KEYRING=${DEB_KEYRING:-"/usr/share/keyrings/devuan-archive-keyring.gpg"}
fi

# Test internet connection
ping -c 2 gnu.org >/dev/null 2>&1 || {
	echo "No internet connection"
	exit 1
}

# Check if the script is not being run as root
if [ "$(id -u)" -eq 0 ]; then
	echo "Please run this script as your regular user."
	exit 1
fi

# Check if 'install' exists in the current dir
[ -x "./install" ] || {
	SCRIPT_DIR=$(dirname "$0")
	cd "${SCRIPT_DIR}" || {
		echo "Failed to change dir to ${SCRIPT_DIR}"
		exit 1
	}
}

export DEBIAN_FRONTEND=noninteractive

# Installs doas and ntp to ensure security updates
if [ "${AUTOMATED}" != 'y' ]; then
	if command -v sudo >/dev/null 2>&1; then
		sudo OGUSER="${USER}" su -c "./dev/setup"
	else
		OGUSER="${USER}" su -c "./dev/setup"
	fi || {
		echo "Failed to setup the system"
		exit 1
	}
fi

echo "Setting up the system."

# Change debian to testing and add unstable to the sources
doas rm -f /etc/apt/sources.list
doas tee /etc/apt/sources.list.d/debian.sources >/dev/null <<EOF
Types: deb
URIs: ${MIRROR}
Suites: stable
Components: main non-free-firmware 
Signed-By: ${DEB_KEYRING}

Types: deb
URIs: ${MIRROR}
Suites: testing
Components: main non-free-firmware 
Signed-By: ${DEB_KEYRING}

Types: deb
URIs: ${MIRROR}
Suites: unstable
Components: main non-free-firmware 
Signed-By: ${DEB_KEYRING}
EOF

# Lower the priority of unstable and stable packages
doas tee /etc/apt/preferences.d/unstable.pref >/dev/null <<'EOF'
Package: *
Pin: release a=testing
Pin-Priority: 990

Package: *
Pin: release a=unstable
Pin-Priority: 10

Package: *
Pin: release a=stable
Pin-Priority: 1
EOF

# Do not install recommended packages automatically
doas tee /etc/apt/apt.conf.d/99norecommends >/dev/null <<EOF
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOF

# Update the system expecting no errors
doas apt-get update -qq || {
	echo "Failed to update the system"
	exit 1
}

# Full system upgrade and install necessary packages
doas apt-get full-upgrade wget apt-transport-https ca-certificates gnupg lsb-release -y --autoremove --purge || {
	echo "Failed to upgrade the system"
	exit 1
}

# Add dreamweaver keyring
if [ ! -f /usr/share/keyrings/dreamweaver.gpg ]; then
	if [ ! -d "${HOME}/.gnupg" ]; then
		remove_gnupg=true
	fi
	doas mkdir -p /usr/share/keyrings
	doas gpg --no-default-keyring --keyring /usr/share/keyrings/dreamweaver.gpg --fingerprint >/dev/null 2>&1
	wget -q -O- "https://h3nc4.com/dreamweaver.asc" | doas gpg --no-default-keyring --keyring /usr/share/keyrings/dreamweaver.gpg --import
fi

# Install dotfiles
wget -q --show-progress --progress=bar -O "/tmp/dotfiles.tar.gz" "https://github.com/h3nc4/dotfiles/releases/latest/download/dotfiles.tar.gz"
wget -q -O "/tmp/dotfiles.tar.gz.asc" "https://github.com/h3nc4/dotfiles/releases/latest/download/dotfiles.tar.gz.asc"
gpg --no-default-keyring --keyring /usr/share/keyrings/dreamweaver.gpg --verify "/tmp/dotfiles.tar.gz.asc" "/tmp/dotfiles.tar.gz" 2>/dev/null
mkdir -p "${HOME}/.config"
tar --strip-components=1 -C "${HOME}/.config" -xf "/tmp/dotfiles.tar.gz"
rm -f "/tmp/dotfiles.tar.gz" "/tmp/dotfiles.tar.gz.asc"

. "${HOME}/.config/env"               # Load environment variables
. "${HOME}/.config/profile.d/install" # Load functions

# Initialize xdg directories
mkdir -p "${XDG_CONFIG_HOME}" "${XDG_DATA_HOME}" "${XDG_CACHE_HOME}"
doas chown -R "${USER}:${USER}" "${XDG_CONFIG_HOME}" "${XDG_DATA_HOME}" "${XDG_CACHE_HOME}"
ln -sf "../.config/bin" "${HOME}/.local/bin"        # Set .local/bin to be the same as .config/bin
echo 'hsts-file = ~/.cache/wget-hsts' >>"${WGETRC}" # Set wget hsts file
touch "${HOME}/.cache/wget-hsts"
rm -f "${HOME}/.wget-hsts"
mkdir -p "${GNUPGHOME}" # Set new GNUPGHOME
doas chown -R "${USER}:${USER}" "${GNUPGHOME}"
find "${GNUPGHOME}" -type d -print0 | xargs -r -0 chmod 700
find "${GNUPGHOME}" -type f -print0 | xargs -r -0 chmod 600
gpg --list-keys >/dev/null # Gen default files if not present already
if [ -n "${remove_gnupg}" ]; then
	rm -rf "${HOME}/.gnupg"
fi

if [ -n "${OPTIONALS}" ]; then
	# Signal setup
	wget -qO- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor | doas tee /etc/apt/keyrings/signal.gpg >/dev/null &&
		doas tee /etc/apt/sources.list.d/signal.sources >/dev/null <<EOF
Types: deb
URIs: https://updates.signal.org/desktop/apt/
Suites: xenial
Components: main 
Signed-By: /etc/apt/keyrings/signal.gpg
EOF
	# Brave setup
	wget -qO- https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg | gpg --dearmor | doas tee /etc/apt/keyrings/brave.gpg >/dev/null &&
		doas tee /etc/apt/sources.list.d/brave.sources >/dev/null <<EOF
Types: deb
URIs: https://brave-browser-apt-release.s3.brave.com/
Suites: stable
Components: main
Signed-By: /etc/apt/keyrings/brave.gpg
EOF
fi

if [ -n "${DEVPACKS}" ]; then
	# Vscodium setup
	wget -qO- https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | doas tee /etc/apt/keyrings/codium.gpg >/dev/null &&
		doas tee /etc/apt/sources.list.d/vscodium.sources >/dev/null <<EOF
Types: deb
URIs: https://download.vscodium.com/debs
Suites: vscodium
Components: main
Signed-By: /etc/apt/keyrings/codium.gpg
EOF
fi

if [ -n "${GAMES}" ]; then
	# Add the non-free and contrib repositories and enable i386
	doas sed -i 's/main/main contrib non-free/g' /etc/apt/sources.list.d/debian.sources
	doas dpkg --add-architecture i386
fi

doas apt-get update -qq
echo "Installing packages. This will take a while."

# Install packages
awk -F, -v enabled="$(printf "core,%s,%s,%s,%s,%s,%s,%s" "${OPTIONALS}" "${DEVPACKS}" "${GAMES}" "${VIRTUALIZATION}" "${XORG}" "${WAYLAND}" "${GUI}")" '
BEGIN {
  n = split(enabled, groups, ",")
  for (i = 1; i <= n; i++) group[groups[i]] = 1
}
group[$1] { print $2 }
' ./packages.csv | xargs doas apt-get install -y

echo "Configuring the system."

# Add user to necessary groups
doas usermod -aG tty,video,audio,disk,input "${USER}"

doas apt-get update -qq & # Populate the command-not-found cache

pipx install yt-dlp bibverse >/dev/null 2>&1 & # Install python packages locally

# Kill spying on firefox
if [ -z "${HEADLESS}" ]; then (
	firefox -no-remote -headless -CreateProfile "me ${HOME}/.mozilla/firefox/me" >/dev/null 2>&1 &&
		rm -rf "${HOME}/.mozilla/firefox/me/"* &&
		wget -qO- https://raw.githubusercontent.com/arkenfox/user.js/master/user.js >"${HOME}/.mozilla/firefox/me/user.js"
) & fi # Since dwm/dwl will call firefox with "firefox -P me" profile.ini can remain unchanged

# Install builds on my repos
if [ -n "${XORG}" ]; then
	weave dwm &
	weave st &
	weave dmenu &
	weave sxac &
fi
if [ -n "${WAYLAND}" ]; then
	weave dwl &
fi

# Setup Nerdfonts
{
	mkdir -p "${HOME}/.cache" "${HOME}/.local/bin" "${HOME}/.local/share/fonts"
	{
		wget -qO- "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz" |
			tar -xJ -C "${HOME}/.local/share/fonts"
	} &
	{
		wget -qO- "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Terminus.tar.xz " |
			tar -xJ -C "${HOME}/.local/share/fonts"
	} &
	wait
	mkfontscale "${HOME}/.local/share/fonts" || :
	mkfontdir "${HOME}/.local/share/fonts" &&
		fc-cache -fv >/dev/null &&
		echo "Hack Nerd Font has been installed"
} &

# Config grub
if [ -d /boot/grub ]; then
	doas tee /etc/default/grub >/dev/null <<EOF
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=Debian
GRUB_CMDLINE_LINUX_DEFAULT="quiet"
GRUB_CMDLINE_LINUX=""
GRUB_DISABLE_OS_PROBER=true
GRUB_BACKGROUND=/boot/grub/end.jpg
EOF
	doas cp pics/end.jpg /boot/grub/
	doas update-grub
fi

# Enable touchpad tapping on Xorg
if [ -n "${XORG}" ]; then
	doas mkdir -p /etc/X11/xorg.conf.d
	doas tee /etc/X11/xorg.conf.d/40-libinput.conf >/dev/null <<'EOF'
Section "InputClass"
Identifier "libinput touchpad catchall"
MatchIsTouchpad "on"
MatchDevicePath "/dev/input/event*"
Driver "libinput"
Option "Tapping" "on"
EndSection
EOF
fi

# Enable periodic trim
doas tee /etc/cron.weekly/fstrim >/dev/null <<'EOF'
#!/bin/sh
{
	echo "===== $(date) ====="
	fstrim --all --verbose
} >>/var/log/fstrim.log 2>&1
EOF
doas chmod +x /etc/cron.weekly/fstrim
doas touch /var/log/fstrim.log
doas chmod 644 /var/log/fstrim.log

# Apply tmux config
(
	tmux new-session -d -s tmp_session
	tmux source-file "${XDG_CONFIG_HOME}/tmux.conf"
	tmux kill-session -t tmp_session
) &

# Config bash
doas rm -f /etc/bash.bashrc "${HOME}/.bashrc" "${HOME}/.bash_profile" "${HOME}/.bash_login" "${HOME}/.bash_logout" "${HOME}/.profile" >/dev/null 2>&1
doas tee /etc/profile >/dev/null <<'EOF'
#!/bin/sh

# Avoid running twice
if [ -n "$PROFILED" ]; then
    return
fi
PROFILED=1

for d in /sbin /usr/sbin /usr/local/sbin /bin /usr/bin /usr/local/bin; do
	case ":${PATH}:" in
	*":${d}:"*) ;;                     # skip if already in PATH
	*) PATH="${d}${PATH:+:${PATH}}" ;; # prepend if not
	esac
done
export PATH

# PS1 is only set for interactive shells
if [ "${PS1-}" ]; then
    if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
        # bash.bashrc sets the default PS1
        if [ -f /etc/bash.bashrc ]; then
            . /etc/bash.bashrc
        fi
    else
        # POSIX shells set their own prompt
        if [ "$(id -u)" -eq 0 ]; then
            PS1='# '
        else
            PS1='$ '
        fi
    fi
fi

if [ -d /etc/profile.d ]; then
    for i in $(run-parts --list --regex '^[a-zA-Z0-9_][a-zA-Z0-9._-]*\.sh$' /etc/profile.d); do
        [ -r "$i" ] && . "$i"
    done
    unset i
fi

if [ -n "$BASH" ]; then
    case $- in
        *i*)  # interactive Bash only
            command_not_found_handle() {
                echo "bash: $1: command not found"
                return 127
            }
            if [ -f "${HOME}/.config/bash/bashrc" ]; then
                . "${HOME}/.config/bash/bashrc"
            fi
            ;;
    esac
fi
EOF
doas ln -sf /etc/profile /etc/bash.bashrc
echo "[ \"\$SHLVL\" -eq 1 ] && [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q" | doas tee /etc/bash.bash_logout >/dev/null

# Config backgrounds
mkdir -p "${HOME}/media/wallpapers"
if [ ! -f "${HOME}/media/wallpapers/landscape.jpg" ]; then
	cp pics/landscape.jpg "${HOME}/media/wallpapers/landscape.jpg"
fi

# Remove beeping noise in tty and others
doas sed -i 's/# set bell-style none/set bell-style none/g' /etc/inputrc
echo "blacklist pcspkr" | doas tee /etc/modprobe.d/blacklist.conf >/dev/null

# Remove login messages
doas rm -f /etc/motd /etc/issue /etc/issue.net >/dev/null 2>&1

# Decrypt multiple partitions with the same key
if [ -f /etc/crypttab ]; then

	# Hook to fix cryptsetup-initramfs not updating /etc/crypttab in initramfs
	doas tee /etc/initramfs-tools/hooks/fix_multiple >/dev/null <<EOF
	#!/bin/sh
	cp /etc/crypttab \${DESTDIR}/cryptroot/crypttab
	exit 0
EOF
	doas chmod +x /etc/initramfs-tools/hooks/fix_multiple

	grep -q ",initramfs,keyscript=decrypt_keyctl" /etc/crypttab >/dev/null 2>&1 ||
		doas sed -i 's/$/,initramfs,keyscript=decrypt_keyctl/g' /etc/crypttab &&
		doas update-initramfs -u
fi

if [ -n "${DEVPACKS}" ]; then
	# Docker
	doas usermod -aG docker "${USER}"
	# Setup initial postgres user and database for development
	doas su - postgres -c "psql -c \"CREATE USER dev WITH SUPERUSER PASSWORD 'dev';\""
	doas su - postgres -c "createdb dev"
	doas su - postgres -c "psql -c \"grant all privileges on database dev to dev;\""
	# Create data dir on vscodium
	CODIUM_DATA_DIR="$(dirname "$(readlink -f /usr/bin/codium)")/../data"
	doas mkdir -p "${CODIUM_DATA_DIR}"
	doas chown "${USER}:${USER}" "${CODIUM_DATA_DIR}"
	# Disable services that are not needed at all times
	if [ -n "${ONSYSTEMD}" ]; then
		doas systemctl disable --now docker.socket
		doas systemctl disable --now docker containerd postgresql
	fi
	# Create a dev user
	doas useradd -m -s /bin/bash dev
	doas mkdir -p /home/dev/.ssh /home/dev/.config
	doas chown -R dev:dev /home/dev/.ssh /home/dev/.config
	doas mv "/home/${USER}/.config" /var/shared-dotconfig
	mkdir -p "/home/${USER}/.config"
	doas bindfs --map=root/${USER}:@root/@${USER} /var/shared-dotconfig "/home/${USER}/.config"
	doas bindfs --map=root/dev:@root/@dev /var/shared-dotconfig /home/dev/.config
	doas tee -a /etc/fstab >/dev/null <<EOF
bindfs#/var/shared-dotconfig /home/${USER}/.config fuse map=root/${USER}:@root/@${USER} 0 0
bindfs#/var/shared-dotconfig /home/dev/.config     fuse map=root/dev:@root/@dev         0 0
EOF
fi

if [ -n "${OPTIONALS}" ] && [ -n "${ONSYSTEMD}" ]; then
	doas systemctl disable --now bluetooth # Disable bluetooth service
fi

if [ -n "${VIRTUALIZATION}" ]; then
	doas virsh net-start default
	doas virsh net-autostart default
	doas usermod -aG libvirt "${USER}"
	doas usermod -aG libvirt-qemu "${USER}"
	doas usermod -aG kvm "${USER}"
	doas usermod -aG input "${USER}"
	echo 'firewall_backend = "iptables"' >/etc/libvirt/network.conf # Use iptables as backend

	# Disable services that are not needed at all times
	if [ -n "${ONSYSTEMD}" ]; then
		doas systemctl disable --now libvirtd-ro.socket libvirtd.socket libvirtd-admin.socket virtlogd.socket virtlogd-admin.socket
		doas systemctl disable --now libvirtd libvirt-guests virtlogd polkit
	fi
fi

# Enable autologin for ttys
if [ -n "${ONSYSTEMD}" ]; then
	for _tty in $( # Systemd
		seq 1 6
	); do
		doas mkdir -p "/etc/systemd/system/getty@tty${_tty}.service.d/"
		doas tee "/etc/systemd/system/getty@tty${_tty}.service.d/override.conf" >/dev/null <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin ${USER} --noclear %I \$TERM
EOF
	done
	if [ "$(cat /proc/1/comm)" = "systemd" ]; then
		doas systemctl daemon-reload
	fi
else
	doas sed -i "s|38400 \(tty[1-6]\)|--autologin ${USER} 38400 \1|" /etc/inittab # Sysvinit
fi

wait # Wait for all background processes to finish

echo "Installation successful"
