#!/bin/env sh

# See LICENSE file for copyright and license details.
# Copyright (C) 2023-2024 Henrique Almeida <me@h3nc4.com>

# This script must be run by your user on a fresh debian net-install
# Select no packages during the installation process
# Preferrably, run this in the same directory as "./run"

while getopts "odgv" opt; do
	case "$opt" in
	o) OPTIONALS=y;;
	d) DEVPACKS=y;;
	g) GAMES=y;;
	v) VIRTUALIZATION=y;;
	*) echo "Usage: $0 [-o] [-d] [-g] [-v]"; exit 1;;
	esac
done

# Test internet connection
ping -c 2 gnu.org >/dev/null 2>&1 || {
	echo "No internet connection"
	exit 1
}

# Check user privileges
sudo -v || {
	echo "This script requires sudo privileges."
	exit 1
}

# Check if the script is not being run as root
[ "$(id -u)" -eq 0 ] && {
	echo "Please run this script as your regular user."
	exit 1
}

# Check if 'run' exists in the current directory
[ -f "./run" ] || {
	SCRIPT_DIR=$(readlink -f "$(dirname "$0")")
	cd "$SCRIPT_DIR" || {
		echo "Failed to change directory to $SCRIPT_DIR"
		exit 1
	}
}

echo "Setting up the system."

. config/env               # Load environment variables
. config/profile.d/install # Load functions

export DEBIAN_FRONTEND=noninteractive

# Config sudo temporarily so the script can run uninterrupted
sudo tee /etc/sudoers >/dev/null <<EOF
Defaults env_keep += "DEBIAN_FRONTEND"
root ALL=(ALL:ALL) ALL
$USER ALL=(ALL:ALL) NOPASSWD:ALL
EOF

# Change debian to testing and add unstable to the sources
sudo sed -i 's/bookworm/testing/g' /etc/apt/sources.list
[ -f /etc/apt/sources.list.d/debian-unstable.list ] ||
echo 'deb http://deb.debian.org/debian unstable main' | sudo tee /etc/apt/sources.list.d/debian-unstable.list >/dev/null

# Lower the priority of unstable packages
sudo tee /etc/apt/preferences.d/unstable.pref >/dev/null <<EOF
Package: *
Pin: release a=testing
Pin-Priority: 990

Package: *
Pin: release a=unstable
Pin-Priority: 10
EOF

# If GAMES is set, add the non-free and contrib repositories and enable i386
[ -n "$GAMES" ] && {
	sudo sed -i 's/main/main contrib non-free/g' /etc/apt/sources.list
	sudo dpkg --add-architecture i386
}

# Do not install recommended packages automatically
sudo tee /etc/apt/apt.conf.d/99norecommends >/dev/null <<EOF
APT::Install-Recommends "0";
APT::Install-Suggests "0";
EOF

# Since the time might be off, update the package list ignoring errors
sudo apt-get update >/dev/null 2>&1

# Set the time so secure connections can be made
sudo apt-get install -y ntpdate -qq
sudo ntpdate -s a.ntp.br || sudo ntpdate -s b.ntp.br || sudo ntpdate -s c.ntp.br

# Update the system expecting no errors
sudo apt-get update -qq || {
	echo "Failed to update the system"
	exit 1
}

# Full system upgrade
sudo apt-get full-upgrade -y --autoremove --purge -qq || {
	echo "Failed to upgrade the system"
	exit 1
}

# Install network and signing packages.
sudo apt-get install -y wget curl apt-transport-https ca-certificates gnupg lsb-release opendoas -qq

# Config doas
sudo tee /etc/doas.conf >/dev/null <<EOF
permit :wheel
permit nopass keepenv root as root
permit nopass nolog keepenv $USER as root 
EOF
sudo chown 0:0 /etc/doas.conf
sudo chmod 400 /etc/doas.conf

SUDO_FORCE_REMOVE=yes doas apt-get remove -y --autoremove --purge sudo -qq
doas rm -rf /etc/sudoers* "$HOME/.sudo"*

# Initialize xdg directories
mkdir -p "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME"
doas chown -R "$USER:$USER" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME"
echo "hsts-file = $HOME/.cache/wget-hsts" >>"$XDG_CONFIG_HOME/wgetrc" # Set wget hsts file

[ -n "$OPTIONALS" ] && {
	# Signal setup
	wget -qO- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor | doas tee /etc/apt/keyrings/signal.gpg >/dev/null &&
	echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/signal.gpg] https://updates.signal.org/desktop/apt xenial main' |
	doas tee /etc/apt/sources.list.d/signal-xenial.list >/dev/null
}

[ -n "$DEVPACKS" ] && {
	# Vscode setup
	wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | doas tee /etc/apt/keyrings/ms.gpg >/dev/null &&
	echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/ms.gpg] https://packages.microsoft.com/repos/vscode stable main" |
	doas tee /etc/apt/sources.list.d/vscode.list >/dev/null
	# Docker setup
	wget -qO- https://download.docker.com/linux/debian/gpg | gpg --dearmor | doas tee /etc/apt/keyrings/docker.gpg >/dev/null &&
	echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" |
	doas tee /etc/apt/sources.list.d/docker.list >/dev/null
}

doas apt-get update -qq
echo "Installing packages. This will take a while."

# Install packages
doas apt-get install -y $(awk -F, -v opt="$OPTIONALS" -v dev="$DEVPACKS" -v games="$GAMES" -v virt="$VIRTUALIZATION" '
	$1 == "core" || ($1 == "opt" && opt == "y") || ($1 == "dev" && dev == "y") || ($1 == "games" && games == "y") || ($1 == "virt" && virt == "y") { print $2 }
' config/packages.csv)

echo "Configuring the system."

# Add user to necessary groups
doas usermod -aG tty,video,audio "$USER"

doas apt-get update -qq & # Populate the command-not-found cache

pipx install yt-dlp >/dev/null 2>&1 & # Install yt-dlp locally

# Kill spying on firefox
(
	firefox -no-remote -headless -CreateProfile "me $HOME/.mozilla/firefox/me" >/dev/null 2>&1 &&
	rm -rf "$HOME/.mozilla/firefox/me/"* &&
	wget -qO- https://raw.githubusercontent.com/arkenfox/user.js/master/user.js >"$HOME/.mozilla/firefox/me/user.js"
) & # Since dwm will call firefox with "firefox -P me" profile.ini can remain unchanged

# Install my builds of dwm, st and dmenu
fromgit https://github.com/h3nc4/dwm dwm &
fromgit https://github.com/h3nc4/st st &
fromgit https://github.com/h3nc4/dmenu dmenu &

# Get latest neovim
get_neovim &

# Setup Nerdfonts
{
	mkdir -p "$HOME/.cache" "$HOME/.local/bin" "$HOME/.local/share/fonts"
	wget -qO- "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Hack.tar.xz" |
	tar -xJ -C "$HOME/.local/share/fonts" &&
	fc-cache -fv >/dev/null &&
	echo "Hack Nerd Font has been installed"
} &

# Firewall rules
doas ufw limit ssh
doas ufw default deny incoming
doas ufw default allow outgoing
echo y | doas ufw enable

# Config grub
doas tee /etc/default/grub >/dev/null <<EOF
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=Debian
GRUB_CMDLINE_LINUX_DEFAULT="quiet"
GRUB_CMDLINE_LINUX=""
GRUB_DISABLE_OS_PROBER=true
GRUB_BACKGROUND=/boot/grub/end.jpg
EOF
doas cp pics/end.jpg /boot/grub/
doas update-grub

# Config Xorg
mkdir -p "$XDG_CONFIG_HOME/X11"
cp config/xinitrc "$XDG_CONFIG_HOME/X11/xinitrc"
touch "$HOME/.config/monitors" # Add a xrandr script to this file

# Enable touchpad tapping
doas mkdir -p /etc/X11/xorg.conf.d
doas tee /etc/X11/xorg.conf.d/40-libinput.conf >/dev/null <<EOF
Section "InputClass"
Identifier "libinput touchpad catchall"
MatchIsTouchpad "on"
MatchDevicePath "/dev/input/event*"
Driver "libinput"
Option "Tapping" "on"
EndSection
EOF

# Config compton
cp config/compton.conf "$XDG_CONFIG_HOME/compton.conf"

# Config gtk
mkdir -p "$XDG_CONFIG_HOME/gtk-3.0" "$XDG_CONFIG_HOME/gtk-2.0"
cp config/gtk/gtk3.conf "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
cp config/gtk/gtk2.conf "$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

# Config polkit
doas tee /etc/polkit-1/rules.d/10-nopasswd.rules >/dev/null <<EOF
polkit.addRule(function(action, subject) {
	if (subject.user == "$USER") {
		return polkit.Result.YES;
	}
});
EOF

# Config bash
doas rm -f /etc/bash.bashrc "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.bash_logout" "$HOME/.profile" >/dev/null 2>&1
mkdir -p "$HOME/.local/profile.d" "$HOME/.config/bash"
cp config/env "$XDG_CONFIG_HOME/env"
cp config/bash/* "$XDG_CONFIG_HOME/bash/"
install -Dm755 config/profile.d/* "$HOME/.local/profile.d/"
doas tee /etc/profile >/dev/null <<EOF
#!/bin/env sh
[ -n "\$PROFILED" ] && return
PROFILED=1
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
[ -d /etc/profile.d ] && for i in /etc/profile.d/*.sh; do . "\$i"; done; unset i
[ "\$BASH" ] && [[ \$- == *i* ]] && {
	function command_not_found_handle (){ echo "bash: \$1: command not found"; return 127; }
	[ -f "\$HOME/.config/bash/bashrc" ] && . "\$HOME/.config/bash/bashrc"
}
EOF
doas ln -s /etc/profile /etc/bash.bashrc
echo "[ \"\$SHLVL\" -eq 1 ] && [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q" | doas tee /etc/bash.bash_logout >/dev/null
ln -sf "$HOME/.local/profile.d/yt" "$HOME/.local/bin/yt"

# Config backgrounds
[ -d "$HOME/media/pics" ] || mkdir -p "$HOME/media/pics"
cp pics/landscape.jpg "$HOME/media/pics/landscape.jpg"

# Create newsboat dirs
mkdir -p "$XDG_DATA_HOME/newsboat" "$XDG_CONFIG_HOME/newsboat"

# Config mpv
mkdir -p "$HOME/.config/mpv"
ln -s "$HOME/.local/bin/yt-dlp" "$HOME/.config/mpv/yt-dlp"
cp config/mpv.conf "$HOME/.config/mpv/mpv.conf"

# Config nsxiv to open all images in a the current dir
doas sed -i 's/Exec=nsxiv/Exec=nsxiv -abf/' /usr/share/applications/nsxiv.desktop

# Config lf
install -Dm755 config/lf/lfprev "$HOME/.local/bin/lfprev"
install -Dm755 config/lf/preview "$HOME/.config/lf/preview"
install -Dm755 config/lf/cleaner "$HOME/.config/lf/cleaner"
cp config/lf/lfrc "$HOME/.config/lf/lfrc"

# Remove beeping noise in tty and others
doas sed -i 's/# set bell-style none/set bell-style none/g' /etc/inputrc
echo "blacklist pcspkr" | doas tee /etc/modprobe.d/blacklist.conf >/dev/null

# Remove login messages
doas rm -f /etc/motd /etc/issue /etc/issue.net >/dev/null 2>&1

# Fix multiple encrypted partitions not being unencrypted at boot
doas tee /etc/initramfs-tools/hooks/fix_multiple >/dev/null <<EOF
#!/bin/env sh
cp /etc/crypttab \${DESTDIR}/cryptroot/crypttab
exit 0
EOF
doas chmod +x /etc/initramfs-tools/hooks/fix_multiple

# Decrypt multiple partitions with the same key
[ -f /etc/crypttab ] && {
	grep -q ",initramfs,keyscript=decrypt_keyctl" /etc/crypttab >/dev/null 2>&1 ||
	doas sed -i 's/$/,initramfs,keyscript=decrypt_keyctl/g' /etc/crypttab &&
	doas update-initramfs -u
}

[ -n "$DEVPACKS" ] && {
	# Docker
	doas groupadd docker
	doas usermod -aG docker "$USER"
	# Setup initial postgres user and database for development
	doas su - postgres -c "psql -c \"CREATE USER dev WITH SUPERUSER PASSWORD 'dev';\""
	doas su - postgres -c "createdb dev"
	doas su - postgres -c "psql -c \"grant all privileges on database dev to dev;\""
	# Disable services that are not needed at all times
	doas systemctl disable --now docker.socket
	doas systemctl disable --now docker containerd postgresql
}

[ -n "$OPTIONALS" ] && doas systemctl disable --now bluetooth # Disable bluetooth service

[ -n "$VIRTUALIZATION" ] && {
	doas virsh net-start default
	doas virsh net-autostart default
	doas usermod -aG libvirt "$USER"
	doas usermod -aG libvirt-qemu "$USER"
	doas usermod -aG kvm "$USER"
	doas usermod -aG input "$USER"
	doas usermod -aG disk "$USER"
	# Dnsmasq must be disabled because it starts on boot and conflicts with libvirt's initialization of dnsmasq
	doas systemctl disable --now dnsmasq
	# Disable services that are not needed at all times
	doas systemctl disable --now libvirtd-ro.socket libvirtd.socket libvirtd-admin.socket virtlogd.socket rpcbind.socket
	doas systemctl disable --now libvirtd libvirt-guests virtlogd rpcbind polkit rtkit-daemon
}

# Enable autologin for ttys 1-6
for ltty in $(seq 1 6); do
	doas "mkdir -p /etc/systemd/system/getty@tty$ltty.service.d/"
	doas "tee /etc/systemd/system/getty@tty$ltty.service.d/override.conf" >/dev/null <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $USER --noclear %I \$TERM
EOF
done
doas systemctl daemon-reload

wait # Wait for all background processes to finish

rm -rf dwm st dmenu # Remove git repos
