#!/bin/sh

mkdir -p /usr/lib/i386-linux-gnu

# Replace sources with testing
echo "deb http://br.deb.devuan.org/merged freia main contrib non-free non-free-firmware" >/etc/apt/sources.list
dpkg --add-architecture i386
apt update

# Core build tools, headers, and 32-bit libs
apt install --autoremove --purge --no-install-recommends -y \
	wget ca-certificates \
	build-essential dkms \
	pkg-config libglvnd-dev linux-headers-amd64 \
	libc6:i386 libstdc++6:i386 libx11-6:i386 libxext6:i386 libgl1:i386 \
	libvulkan1 libvulkan1:i386 libglu1-mesa:i386 libgcc-s1:i386 \
	mesa-vulkan-drivers libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386 \
	xserver-xorg

# Disable nouveau
cat >/etc/modprobe.d/blacklist-nouveau.conf <<'EOF'
blacklist nouveau
options nouveau modeset=0
EOF
update-initramfs -u
init 6

# Download and verify NVIDIA driver
# https://download.nvidia.com/XFree86/Linux-x86_64/latest.txt
wget -q https://us.download.nvidia.com/XFree86/Linux-x86_64/580.126.09/NVIDIA-Linux-x86_64-580.126.09.run
echo "d9c6e8188672f3eb74dd04cfa69dd58479fa1d0162c8c28c8d17625763293475  NVIDIA-Linux-x86_64-580.126.09.run" | sha256sum -c - &&
	chmod +x NVIDIA-Linux-x86_64-580.126.09.run
./NVIDIA-Linux-x86_64-580.126.09.run \
	--kernel-module-type=open \
	--dkms \
	--run-nvidia-xconfig \
	--silent \
	--no-questions \
	--accept-license \
	--no-systemd \
	--rebuild-initramfs

doas tee /etc/modprobe.d/nvidia-pm.conf >/dev/null <<'EOF'
options nvidia NVreg_PreserveVideoMemoryAllocations=1
options nvidia NVreg_TemporaryFilePath=/var/tmp
options nvidia NVreg_EnableGpuFirmware=0
EOF
update-initramfs -u

# Verify GPU and driver
nvidia-smi

# Create suspend script
doas tee /usr/local/bin/nvidia-suspend-mem >/dev/null <<'EOF'
#!/bin/sh
set -e

echo suspend >/proc/driver/nvidia/suspend
echo mem >/sys/power/state
echo resume >/proc/driver/nvidia/suspend
EOF
doas chmod +x /usr/local/bin/nvidia-suspend-mem

apt install --no-install-recommends -y \
	xorg

#!/bin/sh
set -e
wget -q --show-progress "https://developer.download.nvidia.com/compute/cuda/repos/debian13/x86_64/cuda-keyring_1.1-1_all.deb"
doas dpkg -i "cuda-keyring_1.1-1_all.deb"

doas tee /etc/apt/preferences.d/nvidia-cuda.pref >/dev/null <<'EOF'
Package: nvidia-*
Pin: origin developer.download.nvidia.com
Pin-Priority: 1001

Package: firmware-nvidia-*
Pin: origin developer.download.nvidia.com
Pin-Priority: 1001

Package: libnvidia-*
Pin: origin developer.download.nvidia.com
Pin-Priority: 1001

Package: libxnvctrl0
Pin: origin developer.download.nvidia.com
Pin-Priority: 1001
EOF

doas apt update
doas apt install -y nvidia-open linux-headers-amd64

echo "Done. Reboot required."
