#!/bin/sh

doas rm /etc/bash.bashrc "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.bash_logout" "$HOME/.profile" >/dev/null 2>&1
mkdir -p "$HOME/.local/profile.d" "$HOME/.config/bash" "$HOME/.config/tmux"
cp ./config/env "$XDG_CONFIG_HOME/env"
cp ./config/bash/* "$XDG_CONFIG_HOME/bash/"
cp ./config/tmux/* "$XDG_CONFIG_HOME/tmux/"
install -Dm755 ./config/profile.d/* "$HOME/.local/profile.d/"
doas tee /etc/profile >/dev/null <<EOF
[ -n "\$CONFIGUREDRC" ] && return
CONFIGUREDRC=1
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
[ -d /etc/profile.d ] && for i in /etc/profile.d/*.sh; do . "\$i"; done; unset i
[ "\$BASH" ] && [[ \$- == *i* ]] && {
	function command_not_found_handle (){ echo "bash: \$1: command not found"; return 127; }
	[ -f "\$HOME/.config/bash/bashrc" ] && . "\$HOME/.config/bash/bashrc"
}
EOF
doas ln -s /etc/profile /etc/bash.bashrc
echo "[ \"\$SHLVL\" = 1 ] && [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q" | doas tee /etc/bash.bash_logout >/dev/null
