#!/bin/sh
set -e

dev/lint

if [ -z "$(git status --porcelain)" ]; then
	exit 0
fi

echo "Formatting changes detected. Committing and pushing changes..."
git add -A
git commit -m "Apply code formatting [skip ci]"
if [ -n "${CI}" ]; then
	git push origin HEAD
fi
