#!/bin/sh
set -e

DEBIAN_VERSION='12.10.0'
if [ -z "${CI}" ]; then
	PROGRESS_WGET_OPTS='--show-progress --progress=bar'
fi

if [ ! "$(id -u)" -eq 0 ]; then
	echo "Please run this script as root." >&2
	exit 1
fi

OPTIND=1
while getopts "l" opt; do
	case "${opt}" in
	l)
		dev/make_tar
		LOCAL_TAR=y
		;;
	*)
		echo "Usage: $0 [-l]" >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

rm -f "./debian-dreamweaver-${DEBIAN_VERSION}.iso"

if [ ! -f "./debian-${DEBIAN_VERSION}-amd64-netinst.iso" ]; then
	# shellcheck disable=SC2086
	wget -q ${PROGRESS_WGET_OPTS} "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-${DEBIAN_VERSION}-amd64-netinst.iso"
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT
bsdtar -C "${TMPDIR}" -xf "./debian-${DEBIAN_VERSION}-amd64-netinst.iso"
cd "${TMPDIR}"

if [ "${LOCAL_TAR}" = "y" ]; then
	cp "${OLDPWD}/dreamweaver.tar.gz" ./
	cp "${OLDPWD}/dev/cfg/iso.local.install" ./iso.install
	cp "${OLDPWD}/dev/cfg/preseed.local.cfg" ./preseed.cfg
else
	cp "${OLDPWD}/dev/cfg/iso.install" "${OLDPWD}/dev/cfg/preseed.cfg" ./
fi
chmod -w ./iso.install
chmod -w ./preseed.cfg

chmod +w -R ./install.amd/
gunzip ./install.amd/initrd.gz
if [ "${LOCAL_TAR}" = "y" ]; then
	echo dreamweaver.tar.gz | cpio -H newc -o -A -F ./install.amd/initrd
fi
echo preseed.cfg | cpio -H newc -o -A -F ./install.amd/initrd
echo iso.install | cpio -H newc -o -A -F ./install.amd/initrd
gzip ./install.amd/initrd
chmod -w -R ./install.amd/

rm -f preseed.cfg iso.install dreamweaver.tar.gz

TMPSUM="$(mktemp)"
trap 'rm -rf "${TMPDIR}" "${TMPSUM}"' EXIT

chmod +w md5sum.txt
find . -follow -type f ! -name md5sum.txt -print0 | xargs -0 md5sum >"${TMPSUM}"
cp -f "${TMPSUM}" md5sum.txt
chmod -w md5sum.txt

genisoimage -r -J -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -quiet -o "${OLDPWD}/debian-dreamweaver-${DEBIAN_VERSION}.iso" ./

isohybrid "${OLDPWD}/debian-dreamweaver-${DEBIAN_VERSION}.iso"
