#!/bin/sh

SHELL_SCRIPTS=$(find . -type f -not -path "./.git/*" -print0 | xargs -0 grep -Il '^#!' | sort -u)

echo "Checking the following scripts:"
echo "${SHELL_SCRIPTS}"
echo ""
echo "${SHELL_SCRIPTS}" | xargs shellcheck -o all -s sh -e SC1091 -e SC1090 -e SC2312

# shellcheck disable=SC2181
if [ "$?" -eq 0 ]; then
	echo "${SHELL_SCRIPTS}" | xargs shfmt -w
fi

exit $?
