#!/bin/sh
set -e

# Create the tarball in a temporary directory
TMPFILE=$(mktemp --tmpdir tmp.XXXXXXXXXX.tgz)
trap 'rm -f ${TMPFILE}' EXIT

tar --transform 's,^./,Dreamweaver/,' -czf "${TMPFILE}" --exclude=.git* --exclude=*.iso* --exclude=dreamweaver.tgz .

# Move the tarball to the current directory
mv -f "${TMPFILE}" ./dreamweaver.tgz
