export LOADED_BASHRC=1 # Prevents this file from being sourced more than once

# Load local profiles
[ -d "$HOME/.local/profile.d" ] && for i in "$HOME/.local/profile.d/"*; do . "$i"; done
unset i

# Load aliases
. "$HOME/.config/bash/aliases"
# Load functions
. "$HOME/.config/bash/functions"
# Load Keybinds
. "$HOME/.config/bash/keybinds"
# Load variables
. "$HOME/.config/env"

case $- in # Check for an interactive session
*i*) ;;
*) return ;;
esac

# Start X at login
[ "$(tty)" = "/dev/tty1" ] && {
	[ -f /tmp/.Xinit-lock ] && {
		echo "Xorg has restarted. Press Enter to restart Xorg."
		read -r
	}
	touch /tmp/.Xinit-lock
	pidof Xorg >/dev/null 2>&1 || exec startx >/dev/null 2>&1
}

shopt -oq posix && return # If POSIX, return

# Setup dircolors
command -v dircolors >/dev/null && eval "$(dircolors -b)"

# Enable shell completion features
. /usr/share/bash-completion/bash_completion 2>/dev/null || . /etc/bash_completion 2>/dev/null

# Load command not found handler
command_not_found_handle() {
	[ -x /usr/share/command-not-found/command-not-found ] && {
		/usr/share/command-not-found/command-not-found -- "$1"
		return $?
	}
	[ -x /usr/lib/command-not-found ] && {
		/usr/lib/command-not-found -- "$1"
		return $?
	}
	printf "%s: command not found\n" "$1" >&2
	return 127
}

HISTCONTROL=ignoreboth
HISTSIZE=20000
HISTFILESIZE=20000
export HISTFILE="$HOME/.config/bash/history"
shopt -s histappend       # append to history, don't overwrite it
shopt -s checkwinsize     # check the window size after each command
shopt -s globstar         # understand ** as all files in all subdirectories
shopt -s dotglob          # also include hidden files in globbing
complete -cf doas         # complete doas commands
complete -F _command doas # complete doas commandss

# Set the prompt
PROMPT_COMMAND="build_prompt"
build_prompt() {
	local ref
	ref=$(git branch --show-current 2>/dev/null || true)
	PS1="${BOLD}${RED}[${GREEN}\A${BLUE}/${CYAN}\u ${YELLOW}\W${RED}]${WHITE}${ref:+(${RED}$ref${WHITE})}\$ ${RESET}"
}

# Welcome message
[ -f "/tmp/bible.qotd" ] && echo -e "\033[1mWelcome $USER.\nToday is $(\date '+%A, %B %d, %Y').\033[0m$(cat /tmp/bible.qotd)\033[1m\n" || {
	(
		bibverse >/tmp/bible.qotd 2>/dev/null &&
			sed -i '1s/^/\n\n/' /tmp/bible.qotd &&       # Add two new lines at the beginning
			sed -i 's/\(.*\)—/\1\n\t— /' /tmp/bible.qotd # Add a new line and tab before the last dash
	) &
}

# Start tmux at login
[ -z "$TMUX" ] && [ "$(tty)" != "/dev/tty6" ] && exec tmux new-session -s "session-$(\date +'%Y%m%d-%H%M%S-%3N')"
