#!/bin/sh

apt-get update -qq

apt-get install -y ntp ntpdate opendoas || exit 1

# sync time
/usr/sbin/ntpdate -s time.nist.gov

# If OGUSER is not set, set it to the user 1000
OGUSER=${OGUSER:-$(id -un 1000)}

# Config doas
tee /etc/doas.conf >/dev/null <<_EOF
permit :wheel
permit nopass keepenv root as root
permit nopass nolog keepenv $OGUSER as root 
_EOF
chown 0:0 /etc/doas.conf
chmod 400 /etc/doas.conf
