#!/bin/sh
#
# Copyright (C) 2026  Henrique Almeida <me@h3nc4.com>
#
# This file is part of Dreamweaver.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# A VM you drive yourself, on a screen you can see. Asserts nothing, unlike every other
# script here, which is headless.
#
# The screen is a browser page, served by websockify off QEMU's own RFB stream: one process,
# one port, no VNC client. Open the URL this prints. -V publishes the raw RFB port too.
#
# The host needs only Docker, or nothing at all from inside the dev container.
#
# Boot order is disk then medium, so one run covers the whole journey: an empty disk falls
# through to the ISO, and the installer's closing reboot finds a disk that boots.
#
# The disk persists under scratch/vm/. -r throws it away.

set -e

cd "$(dirname "$0")/../"

FIRMWARE='bios'
MEMORY='4096'
CPUS='4'
DISK_SIZE='20G'
PORT='6080'
VNC_PORT=''
BIND='0.0.0.0'
OUT_DIR='scratch/vm'
RESET=''
DISK_ONLY=''

DEV_IMAGE_REPO="${DEV_IMAGE_REPO:-${DOCKERHUB_USERNAME:-h3nc4}/dreamweaver-dev}"

die() {
	echo "$0: $*" >&2
	exit 1
}

usage() {
	cat >&2 <<-EOF
		Usage: $0 [-f bios|uefi] [-m MiB] [-c cpus] [-s size] [-p port] [-V port]
		          [-l] [-o dir] [-r] [-b] [<image.iso>]

		  -f  firmware to boot (default: ${FIRMWARE})
		  -m  guest memory in MiB (default: ${MEMORY})
		  -c  guest cpus (default: ${CPUS})
		  -s  disk size, created on first run (default: ${DISK_SIZE})
		  -p  host port to serve the browser viewer on (default: ${PORT})
		  -V  also publish the raw RFB port here, for a real VNC client
		  -l  bind the ports to localhost only, for use over an ssh tunnel
		  -o  where to keep the disk, the firmware vars and the runner (default: ${OUT_DIR})
		  -r  reset: delete the disk and start the install over
		  -b  boot the disk with no medium attached

		The image is the one this repo builds. Use the interactive one, which is the
		default from scripts/build-iso.sh; an image built with -t answers the questions
		for you, which is the opposite of the point here.

		The screen is a web page: open http://<host>:${PORT}/vnc.html and nothing needs
		installing. The terminal this leaves you at is QEMU's monitor: \`quit\` stops the
		VM, \`screendump out.ppm\` takes a picture, \`sendkey ret\` presses a key.
	EOF
	exit 1
}

OPTIND=1
while getopts 'f:m:c:s:p:V:lo:rb' opt; do
	case "${opt}" in
	f) FIRMWARE="${OPTARG}" ;;
	m) MEMORY="${OPTARG}" ;;
	c) CPUS="${OPTARG}" ;;
	s) DISK_SIZE="${OPTARG}" ;;
	p) PORT="${OPTARG}" ;;
	V) VNC_PORT="${OPTARG}" ;;
	l) BIND='127.0.0.1' ;;
	o) OUT_DIR="${OPTARG}" ;;
	r) RESET='y' ;;
	b) DISK_ONLY='y' ;;
	*) usage ;;
	esac
done
shift $((OPTIND - 1))

case "${FIRMWARE}" in
bios | uefi) ;;
*) die "unknown firmware '${FIRMWARE}'" ;;
esac

ISO="$1"

if [ -n "${DISK_ONLY}" ]; then
	ISO=''
else
	[ -n "${ISO}" ] || usage
fi

# A path outside the repo is invisible in the container, where QEMU's own failure is
# confusing.
if [ -n "${ISO}" ]; then
	case "${ISO}" in
	/*)
		_root="$(pwd)"
		case "${ISO}" in
		"${_root}"/*) ISO="${ISO#"${_root}"/}" ;;
		*) die "${ISO} is outside the repository; copy it in, or pass a relative path" ;;
		esac
		;;
	*) ;;
	esac
	[ -s "${ISO}" ] || die "${ISO} is missing or empty"
fi

mkdir -p "${OUT_DIR}"

################################################################################
# The guest side, written out rather than inlined: QEMU, qemu-img and OVMF all live in the
# container. It goes inside the workspace, so the container sees it immediately.

RUNNER="${OUT_DIR}/run.sh"

cat >"${RUNNER}" <<EOF
#!/bin/sh
# Generated by scripts/vm.sh. Edits are lost on the next run.

set -e

FIRMWARE='${FIRMWARE}'
MEMORY='${MEMORY}'
CPUS='${CPUS}'
DISK_SIZE='${DISK_SIZE}'
OUT_DIR='${OUT_DIR}'
ISO='${ISO}'
RESET='${RESET}'
EOF

cat >>"${RUNNER}" <<'EOF'

DISK="${OUT_DIR}/disk.qcow2"

die() {
	echo "vm: $*" >&2
	exit 1
}

[ -n "${RESET}" ] && rm -f "${DISK}" "${OUT_DIR}/uefi-vars.fd"

if [ ! -f "${DISK}" ]; then
	echo "creating ${DISK} (${DISK_SIZE})"
	qemu-img create -q -f qcow2 "${DISK}" "${DISK_SIZE}"
fi

################################################################################
# The viewer. websockify serves noVNC's page and proxies the browser's WebSocket to QEMU's
# RFB port, so one process covers both halves. It starts before QEMU and is killed on the
# way out, with its output in a log rather than in the middle of the QEMU monitor this
# terminal becomes. A browser that will not connect is diagnosed there.

command -v websockify >/dev/null 2>&1 ||
	die 'websockify not found. This image predates the browser viewer;
    rebuild it with ./scripts/build-dev-image.sh'

[ -s /usr/share/novnc/vnc.html ] ||
	die 'noVNC is not installed in this image; rebuild it with ./scripts/build-dev-image.sh'

websockify --web /usr/share/novnc 0.0.0.0:6080 127.0.0.1:5900 \
	>"${OUT_DIR}/novnc.log" 2>&1 &
WS_PID="$!"

# Not exec'd below, so this runs: QEMU exiting has to take the viewer with it.
trap 'kill "${WS_PID}" 2>/dev/null || :' EXIT INT TERM

# TCG boots the same image, only too slowly to sit through an install.
ACCEL='tcg'
CPU='max'
if [ -r /dev/kvm ] && [ -w /dev/kvm ]; then
	ACCEL='kvm'
	CPU='host'
else
	echo "Warning: no usable /dev/kvm; falling back to TCG. This will be painful." >&2
fi

set -- \
	-machine "q35,accel=${ACCEL}" \
	-cpu "${CPU}" \
	-m "${MEMORY}" \
	-smp "${CPUS}" \
	-drive "file=${DISK},format=qcow2,if=none,id=hd0" \
	-device virtio-blk-pci,drive=hd0,bootindex=0 \
	-netdev user,id=net0 \
	-device virtio-net-pci,netdev=net0 \
	-device qemu-xhci,id=xhci \
	-device usb-tablet,bus=xhci.0 \
	-vga std \
	-global VGA.vgamem_mb=32 \
	-vnc "0.0.0.0:0" \
	-monitor stdio \
	-name 'Dreamweaver'

# Both drives are if=none with a separate -device, because bootindex belongs to the device:
# `if=virtio,bootindex=0` is rejected with "does not support the option 'bootindex'".

# usb-tablet reports absolute coordinates. Without it the guest gets relative motion and
# the cursor drifts from the mouse as soon as anything clickable is drawn.

# vgamem_mb=32 buys the modes a desktop wants. The 16 MiB default letterboxes dwm.

if [ -n "${ISO}" ]; then
	set -- "$@" \
		-drive "file=${ISO},format=raw,if=none,id=cd,media=cdrom,readonly=on" \
		-device ide-cd,drive=cd,bootindex=1
fi

# Persisted across runs: a UEFI install writes its boot entry to NVRAM, and a fresh store
# would lose it and drop to the shell.
if [ "${FIRMWARE}" = 'uefi' ]; then
	OVMF_CODE=''
	for dir in /usr/share/OVMF /usr/share/ovmf /usr/share/qemu; do
		for code in OVMF_CODE_4M.fd OVMF_CODE.fd OVMF.fd; do
			if [ -f "${dir}/${code}" ]; then
				OVMF_CODE="${dir}/${code}"
				break
			fi
		done
		[ -n "${OVMF_CODE}" ] && break
	done
	[ -n "${OVMF_CODE}" ] || die 'no OVMF firmware in this image'

	if [ ! -f "${OUT_DIR}/uefi-vars.fd" ]; then
		OVMF_VARS=''
		for dir in /usr/share/OVMF /usr/share/ovmf; do
			for vars in OVMF_VARS_4M.fd OVMF_VARS.fd; do
				if [ -f "${dir}/${vars}" ]; then
					OVMF_VARS="${dir}/${vars}"
					break
				fi
			done
			[ -n "${OVMF_VARS}" ] && break
		done
		[ -n "${OVMF_VARS}" ] || die 'no OVMF variable store in this image'
		cp -f "${OVMF_VARS}" "${OUT_DIR}/uefi-vars.fd"
	fi

	set -- \
		-drive "if=pflash,format=raw,unit=0,readonly=on,file=${OVMF_CODE}" \
		-drive "if=pflash,format=raw,unit=1,file=${OUT_DIR}/uefi-vars.fd" \
		"$@"
fi

# Deliberately not exec'd: the EXIT trap above is what stops the viewer.
qemu-system-x86_64 "$@"
EOF

chmod +x "${RUNNER}"

################################################################################

echo "################################################################"
echo "# firmware: ${FIRMWARE}    ram: ${MEMORY} MiB    cpus: ${CPUS}"
echo "# disk:     ${OUT_DIR}/disk.qcow2${RESET:+  (reset)}"
echo "# medium:   ${ISO:-none, booting the disk}"
echo "#"
# autoconnect skips the connect button. resize=scale fits a 1280x800 guest in a smaller
# window.
#
# The first address rather than the hostname, since this gets opened from another machine
# where a short hostname may not resolve. `hostname` is the fallback without -I.
_host="$(hostname -I 2>/dev/null | awk '{print $1}')"
[ -n "${_host}" ] || _host="$(hostname)"
[ "${BIND}" = '127.0.0.1' ] && _host='localhost'
echo "# screen:   http://${_host}:${PORT}/vnc.html?autoconnect=1&resize=scale"
[ -n "${VNC_PORT}" ] && echo "# rfb:      ${BIND}:${VNC_PORT}  (for a VNC client)"
if [ "${BIND}" = '127.0.0.1' ]; then
	echo "#           ssh -N -L ${PORT}:127.0.0.1:${PORT} $(id -un)@$(hostname)"
fi
echo "#"
echo "# This terminal is QEMU's monitor. \`quit\` stops the VM."
echo "################################################################"

# Already in the dev container: no second container, and no Docker needed at all.
if command -v qemu-system-x86_64 >/dev/null 2>&1; then
	exec "./${RUNNER}"
fi

command -v docker >/dev/null 2>&1 ||
	die 'no qemu-system-x86_64 and no docker; run this from the host or the dev container'

dev_image_tag="${DEV_IMAGE_TAG:-$(./scripts/devcontainer-image.sh -t)}"
DEV_IMAGE="${DEV_IMAGE_REPO}:${dev_image_tag}"

if ! docker image inspect "${DEV_IMAGE}" >/dev/null 2>&1; then
	echo "$0: ${DEV_IMAGE} is not present locally." >&2
	_have="$(docker images "${DEV_IMAGE_REPO}" --format '{{.Tag}}' | tr '\n' ' ')"
	[ -n "${_have}" ] && echo "Tags that are here: ${_have}" >&2
	echo "Build it with \`./scripts/build-dev-image.sh\`, or set DEV_IMAGE_TAG." >&2
	exit 1
fi

# A tty makes the monitor usable, but `docker run -t` fails without one, so a piped
# monitor script still works: `printf 'screendump s.ppm\nquit\n' | ...`
TTY_FLAG='-i'
[ -t 0 ] && TTY_FLAG='-it'

set -- \
	--name "dreamweaver-vm-${PORT}" \
	--device /dev/kvm \
	-e "HOST_UID_GID=$(id -u):$(id -g)" \
	-v "$(pwd):/workspaces/Dreamweaver" \
	-p "${BIND}:${PORT}:6080"

# QEMU binds RFB on all interfaces inside the container, not loopback: a published port is
# NAT'd to the container's address, which a 127.0.0.1 listener would not answer.
[ -n "${VNC_PORT}" ] && set -- "$@" -p "${BIND}:${VNC_PORT}:5900"

# --device rather than --privileged: KVM is the only host device a VM needs.
exec docker run --rm "${TTY_FLAG}" "$@" "${DEV_IMAGE}" "./${RUNNER}"
