#!/bin/sh
set -ef

user_host="${USER}@$(hostname)"
bat_folder="$(find /sys/class/power_supply/ -maxdepth 2 -name 'BAT*' -print -quit)"

if [ -d "${bat_folder}" ]; then
	while :; do
		read -r capacity <"${bat_folder}/capacity"
		read -r status <"${bat_folder}/status"
		xsetroot -name " $(date) | ${capacity}% (${status}) | ${user_host} "
		sleep 1
	done
fi

while :; do
	xsetroot -name " $(date) | ${user_host} "
	sleep 1
done
