#!/bin/sh

if xrandr | grep "HDMI-A-0 connected" >/dev/null; then
	xrandr --output HDMI-A-0 --primary --mode 1920x1080 --left-of eDP
else 
	xrandr --output HDMI-A-0 --off --output eDP  --scale 1x1 --auto
fi
pkill -USR1 dyn-wallpapers
