. "$HOME/.config/env"

xset +fp "$HOME/.local/share/fonts/"
xset fp rehash

"$HOME/.config/X11/dyn-wallpapers" &
"$HOME/.config/X11/dyn-status" &
"$HOME/.config/X11/monitors"

# Composer
compton &

exec dwm
