name: Automerge Renovate

on:
  workflow_run:
    workflows:
      - Dreamweaver Boot Test
      - Dreamweaver Development CI
      - Security Analysis
    types:
      - completed

permissions: {}

jobs:
  automerge:
    name: Merge if CI passed
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run h3nc4/renovate-automerge-action
        uses: h3nc4/renovate-automerge-action@7fe8848099599af579342387aeb1d05bc8f86e94 # v1
        with:
          private-key: ${{ secrets.AUTOMERGE_APP_PRIVATE_KEY }}
