name: Run CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --no-install-recommends \
            ca-certificates \
            git \
            shellcheck \
            shfmt
      - uses: actions/checkout@v4
      - name: Ignore folder ownership
        run: git config --global --add safe.directory '*'
      - name: Run check
        run: ./dev/ci
